version: '3'
services: 
 web:
  build: 
   context: .
   dockerfile: Dockerfile.dev
  ports: 
   - "3000:3000"
  volumes: 
    # not mapping nodemodules folder inside container
    - /app/node_modules
    #map current folder outside the container to current folder app inside the container
    - .:/app 
 tests: 
    build: 
     context: .
     dockerfile: Dockerfile.dev
    volumes: 
    # not mapping nodemodules folder 
      - /app/node_modules
    #map current folder outside the container to current folder app inside the container
      - .:/app 
    command: ["npm","run","test"]